version: '3.8'
services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
  myshop:
    build:
      context: .
      dockerfile: MyShop/Dockerfile
    container_name: myshop
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - redis
