version: '3.8'
services:
  redis:
    image: redis:7.2
    container_name: redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=yourStrongRedisPassword
  myshop:
    build:
      context: .
      dockerfile: MyShop/Dockerfile
    container_name: myshop
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - REDIS_PASSWORD=yourStrongRedisPassword
    depends_on:
      - redis
